<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Паспортизация ВСП/РФ</Title>
    <Description>Ведение сведений об объектах недвижимости региональной сети</Description>
    <Version>0.0.0-local</Version>
    <Owners>ЦК Развития портальных систем</Owners>
    <Authors>$(Owners)</Authors>
    <Company>РСХБ</Company>
    <ProjectUrl Condition="'$(CI_PROJECT_URL)' != '' ">$(CI_PROJECT_URL)</ProjectUrl>
    <PackageProjectUrl>$(ProjectUrl)</PackageProjectUrl>
    <OutputType>Library</OutputType>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.8" />
  </ItemGroup>

</Project>
