<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net9.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
	  <Title>Паспортизация ВСП/РФ</Title>
	  <Description>Ведение сведений об объектах недвижимости региональной сети</Description>
	  <Version>0.0.0-local</Version>
	  <Owners>ЦК Развития портальных систем</Owners>
	  <Authors>$(Owners)</Authors>
	  <Company>РСХБ</Company>
	  <tags></tags>
	  <ProjectUrl Condition="'$(CI_PROJECT_URL)' != '' ">$(CI_PROJECT_URL)</ProjectUrl>
	  <PackageProjectUrl>$(ProjectUrl)</PackageProjectUrl>
	  <OutputType>Library</OutputType>
	  <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.8" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Frame.Shared\Frame.Shared.csproj" />
    <ProjectReference Include="..\Westwind.Scripting\Westwind.Scripting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
